### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by MADECICCO** [stevejcl/dwarfii-stellarium-goto#156]
HI I have tried to use it,UBUNTU 20.0, firefox , stellarium.

Sometimes IP is lost.
 I have to use app tablet to see images in the http\ window, sometimes not.

Testing astro mode after clicking button start a capture that never ends, so I had to close terminal and reinitiate all procedures.

Goto using stellarium does not work, despite it is conected succesfully etc.

**Comment by acocalypso** [comment]
We will take a look into it.

Which version did you use.
Did you use the compiled version or straight from source?

**Comment by acocalypso** [comment]
Closed as we got no feedback
